version: "3.5"
services:
  mysql:
    image: mysql:8
    container_name: seata
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']