apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: seatabusiness
  name: seatabusiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatabusiness
      env: dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seatabusiness
        env: dev
    spec:
      containers:
      - image: pjhu/business:1.0
        env:
          - name: MYSQL_HOST
            value: mysql
        name: seatabusiness

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: seatabusiness
    env: dev
  name: seatabusiness
spec:
  ports:
  - name: seatabusiness
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: remotebusiness
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: seatabusiness
    env: dev
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: business-ingress
  namespace: dev
 
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /business
        pathType: Prefix
        backend:
          service:
            name: seatabusiness
            port:
              number: 8080
