---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: mysql
    env: dev
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    env: dev
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      env: dev
  template:
    metadata:
      labels:
        app: mysql
        env: dev
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"