apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: seataorder
  name: seataorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seataorder
      env: dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seataorder
        env: dev
    spec:
      containers:
      - image: pjhu/order:1.0
        env:
          - name: MYSQL_HOST
            value: mysql
        name: seataorder

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: seataorder
    env: dev
  name: seataorder
spec:
  ports:
  - name: seataorder
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: seataorder
    env: dev
  type: ClusterIP
