apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: seataorder
  name: seataorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seataorder
      env: dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seataorder
        env: dev
    spec:
      containers:
      - image: pjhu/order:1.0
        env:
          - name: MYSQL_HOST
            value: mysql
        name: seataorder

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: seataorder
    env: dev
  name: seataorder
spec:
  ports:
  - name: seataorder
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: seataorder
    env: dev
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-ingress
  namespace: dev
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: seataorder
            port:
              number: 8080