version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes: 
      - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  nacos:
    image: nacos/nacos-server:1.4.2
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123
      - MYSQL_SERVICE_DB_PARAM=allowPublicKeyRetrieval=true&characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      - NACOS_DEBUG=y
    volumes:
      - ./custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    depends_on:
      - mysql
    restart: always
  
  seata:
    image: seataio/seata-server:1.4.2
    container_name: seata
    volumes:
      - ../../mysql-connector-java-8.0.25.jar:/seata-server/libs/mysql-connector-java-8.0.25.jar 
      - ../../local/nacos/registry.conf:/seata-server/resources/registry.conf
      - ../../local/nacos/file.conf:/seata-server/resources/file.conf
    environment:
      - SEATA_IP=192.168.0.108
      - SEATA_PORT=8091
      - STORE_MODE=db
    ports:
      - 8091:8091
    depends_on:
      - mysql
      - nacos
    restart: always

