---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:spring-cloud-k8s
  namespace: nacos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spring-cloud-k8s
subjects:
- kind: ServiceAccount
  name: default
  namespace: nacos